title = "tscott0"
baseurl = "https://tscott0.github.io"
languageCode = "en-gb"

theme = "beautifulhugo"
PygmentsCodeFences = true
PygmentsStyle = "friendly"

[Params]
  subtitle = "Gopher, clacker, human"
  logo = "img/logo.png"
  commit = false

[Author]
  name = "Tom Scott"
  email = "tomscott87@gmail.com"
  github = "tscott0"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3
